### ISSUE TITLE
Hotkey F7 doesn't match

### ISSUE THREAD

**Issue by l1fecoach** [BrandenEK/Blasphemous-Rando-Map#4]
I'm not sure but on my System it is F1. Haven't changed anything. F7 don't work for me. If someone is also looking for a searching Hotkey

**Comment by BrandenEK** [comment]
You are correct, it is currently F1 on the current version.  But I'm actually about to release a new version of the mod where the default is changed to F7.  I just updated the documentation yesterday, so you just happened to look at it right after I changed it to the new version.
